---
#
# GUI File Managers
#

- name: Install | Thunar
  ansible.builtin.package:
    name: '{{ __filemanagers_thunar_package }}'
    state: present
  when:
    - filemanagers_thunar_enabled | bool
    - __filemanagers_thunar_package | default('') | length > 0
  retries: 3
  delay: 5

- name: Install | Dolphin
  ansible.builtin.package:
    name: '{{ __filemanagers_dolphin_package }}'
    state: present
  when:
    - filemanagers_dolphin_enabled | bool
    - __filemanagers_dolphin_package | default('') | length > 0
  retries: 3
  delay: 5

- name: Install | Nautilus
  ansible.builtin.package:
    name: '{{ __filemanagers_nautilus_package }}'
    state: present
  when:
    - filemanagers_nautilus_enabled | bool
    - __filemanagers_nautilus_package | default('') | length > 0
  retries: 3
  delay: 5

- name: Install | PCManFM
  ansible.builtin.package:
    name: '{{ __filemanagers_pcmanfm_package }}'
    state: present
  when:
    - filemanagers_pcmanfm_enabled | bool
    - __filemanagers_pcmanfm_package | default('') | length > 0
  retries: 3
  delay: 5

- name: Install | Nemo
  ansible.builtin.package:
    name: '{{ __filemanagers_nemo_package }}'
    state: present
  when:
    - filemanagers_nemo_enabled | bool
    - __filemanagers_nemo_package | default('') | length > 0
  retries: 3
  delay: 5

- name: Install | Double Commander
  ansible.builtin.package:
    name: '{{ __filemanagers_doublecmd_package }}'
    state: present
  when:
    - filemanagers_doublecmd_enabled | bool
    - __filemanagers_doublecmd_package | default('') | length > 0
  retries: 3
  delay: 5
