---
#
# i3 Installation
#

- name: i3 | Build package list
  ansible.builtin.set_fact:
    __desktop_environment_i3_install_packages: >-
      {{
        __desktop_environment_i3_packages +
        [__desktop_environment_i3_status_packages[desktop_environment_i3_status] | default('')] +
        (desktop_environment_i3_dmenu_enabled | bool | ternary([__desktop_environment_i3_dmenu_package], [])) +
        (desktop_environment_i3_picom_enabled | bool | ternary([__desktop_environment_i3_picom_package], []))
      }}

- name: i3 | Filter empty packages
  ansible.builtin.set_fact:
    __desktop_environment_i3_install_packages: >-
      {{ __desktop_environment_i3_install_packages | select('string') | reject('equalto', '') | list }}

- name: i3 | Install packages
  ansible.builtin.package:
    name: '{{ __desktop_environment_i3_install_packages }}'
    state: present
  when:
    - __desktop_environment_i3_install_packages | length > 0
  retries: 3
  delay: 5
