---
#
# LXQt Installation
#

- name: LXQt | Pick variant package set
  ansible.builtin.set_fact:
    __desktop_environment_lxqt_variant_packages: >-
      {{
        __desktop_environment_lxqt_minimal_packages
        if desktop_environment_lxqt_variant == 'minimal'
        else __desktop_environment_lxqt_full_packages
      }}

- name: LXQt | Build package list
  ansible.builtin.set_fact:
    __desktop_environment_lxqt_install_packages: >-
      {{
        __desktop_environment_lxqt_variant_packages +
        [__desktop_environment_lxqt_icon_packages[desktop_environment_lxqt_icons] | default('')]
      }}

- name: LXQt | Filter empty packages
  ansible.builtin.set_fact:
    __desktop_environment_lxqt_install_packages: >-
      {{ __desktop_environment_lxqt_install_packages | select('string') | reject('equalto', '') | list }}

- name: LXQt | Install packages
  ansible.builtin.package:
    name: '{{ __desktop_environment_lxqt_install_packages }}'
    state: present
  when:
    - __desktop_environment_lxqt_install_packages | length > 0
  retries: 3
  delay: 5
