---
#
# Shell Main Tasks
#

- name: Main | Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'
  tags:
    - shell
    - shell:vars

- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  when: shell_enabled | bool
  tags:
    - shell
    - shell:install

- name: Main | Import Oh My Zsh tasks
  ansible.builtin.import_tasks: ohmyzsh.yml
  when:
    - shell_enabled | bool
    - shell_zsh_enabled | bool
    - shell_zsh_framework == 'ohmyzsh'
  tags:
    - shell
    - shell:ohmyzsh

- name: Main | Import user tasks
  ansible.builtin.import_tasks: users.yml
  when:
    - shell_enabled | bool
    - shell_default != 'bash'
  tags:
    - shell
    - shell:users
