---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify | Load OS-specific variables
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - files:
            - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
            - '{{ ansible_facts["os_family"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
            - '{{ ansible_facts["distribution"] }}.yml'
            - '{{ ansible_facts["os_family"] }}.yml'
          paths:
            - '../../vars'

    #
    # Thunar
    #

    - name: Verify | Check Thunar installed (Arch)
      ansible.builtin.command:
        cmd: pacman -Q {{ __filemanagers_thunar_package }}
      register: __verify_thunar_arch
      changed_when: false
      failed_when: __verify_thunar_arch.rc != 0
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Verify | Check Thunar installed (Debian)
      ansible.builtin.command:
        cmd: dpkg -l {{ __filemanagers_thunar_package }}
      register: __verify_thunar_debian
      changed_when: false
      failed_when: __verify_thunar_debian.rc != 0
      when: ansible_facts['os_family'] == 'Debian'

    - name: Verify | Check Thunar installed (RedHat)  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: rpm -q {{ __filemanagers_thunar_package }}
      register: __verify_thunar_redhat
      changed_when: false
      failed_when: __verify_thunar_redhat.rc != 0
      when: ansible_facts['os_family'] == 'RedHat'
