---
#
# Arch Linux Variables
#

# Terminal emulator packages
__terminal_packages:
  ghostty: 'ghostty'
  alacritty: 'alacritty'
  kitty: 'kitty'
  foot: 'foot'
  wezterm: 'wezterm'
  konsole: 'konsole'
  gnome-terminal: 'gnome-terminal'

# Kitty extras for image support
__terminal_kitty_image_packages:
  - 'imagemagick'
