---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    keepassxc_enabled: true
    keepassxc_secret_service_enabled: true
    keepassxc_secret_service_scope: 'global'  # pragma: allowlist secret
    keepassxc_autostart_enabled: true
    keepassxc_users:
      - name: 'testuser'
        mode: 'managed'

  tasks:
    - name: Converge | Include keepassxc role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
