---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify | Check pipewire package installed (Arch)
      ansible.builtin.command:
        cmd: 'pacman -Q pipewire'
      register: __verify_pipewire_arch
      changed_when: false
      failed_when: __verify_pipewire_arch.rc != 0
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Verify | Check wireplumber package installed (Arch)
      ansible.builtin.command:
        cmd: 'pacman -Q wireplumber'
      register: __verify_wireplumber_arch
      changed_when: false
      failed_when: __verify_wireplumber_arch.rc != 0
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Verify | Check pipewire package installed (Debian)
      ansible.builtin.command:
        cmd: 'dpkg -l pipewire'
      register: __verify_pipewire_deb
      changed_when: false
      failed_when: __verify_pipewire_deb.rc != 0
      when: ansible_facts['os_family'] == 'Debian'

    - name: Verify | Check pipewire package installed (RedHat)  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: 'rpm -q pipewire'
      register: __verify_pipewire_rpm
      changed_when: false
      failed_when: __verify_pipewire_rpm.rc != 0
      when: ansible_facts['os_family'] == 'RedHat'
