---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    cad_enabled: true
    cad_openscad_enabled: true
    cad_freecad_enabled: true
    cad_librecad_enabled: true
    cad_qcad_enabled: true
    cad_blender_enabled: true
    cad_kicad_enabled: true

  tasks:
    - name: Converge | Include cad role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
