---
- name: Install | Build package list
  ansible.builtin.set_fact:
    __bluetooth_install_packages: >-
      {{
        __bluetooth_packages +
        ((bluetooth_deprecated_tools | bool and __bluetooth_deprecated_package | length > 0)
          | ternary([__bluetooth_deprecated_package], [])) +
        (bluetooth_obex | bool | ternary([__bluetooth_obex_package], [])) +
        (__bluetooth_audio_packages[bluetooth_audio] | default([])) +
        (__bluetooth_gui_packages[bluetooth_gui] | default([]))
      }}

- name: Install | Filter empty package names
  ansible.builtin.set_fact:
    __bluetooth_install_packages: >-
      {{ __bluetooth_install_packages | select('string') | reject('equalto', '') | list }}

- name: Install | Install packages
  ansible.builtin.package:
    name: '{{ __bluetooth_install_packages }}'
    state: present
  when: __bluetooth_install_packages | length > 0

- name: Install | Install AUR audio packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: '{{ __bluetooth_aur_packages.alsa }}'
    state: present
  when:
    - ansible_facts['os_family'] == 'Archlinux'
    - bluetooth_audio == 'alsa'
