---
- name: Main | Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'
  tags:
    - bluetooth

- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  when: bluetooth_enabled | bool
  tags:
    - bluetooth
    - bluetooth:install

- name: Main | Import configure tasks
  ansible.builtin.import_tasks: configure.yml
  when: bluetooth_enabled | bool
  tags:
    - bluetooth
    - bluetooth:configure

- name: Main | Import service tasks
  ansible.builtin.import_tasks: service.yml
  when: bluetooth_enabled | bool
  tags:
    - bluetooth
    - bluetooth:service
