---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    bluetooth_enabled: true
    bluetooth_service_enabled: false
    bluetooth_deprecated_tools_enabled: false
    bluetooth_obex_enabled: true
    bluetooth_audio: 'pipewire'
    bluetooth_gui: 'none'
    bluetooth_auto_enable: true
    bluetooth_discoverable_timeout: 180
    bluetooth_pairable_timeout: 180
    bluetooth_always_pairable: false
    bluetooth_privacy: 'device'
    bluetooth_secure_connections: 'on'
    bluetooth_controller_mode: 'dual'
    bluetooth_name_resolving: true
    bluetooth_temporary_timeout: 30
    bluetooth_fast_connectable: false
    bluetooth_reconnect_attempts: 7
    bluetooth_reconnect_intervals: '1,2,4,8,16,32,64'
    bluetooth_resume_delay: 2
    bluetooth_gatt_cache: 'always'
    bluetooth_gatt_channels: 3
    bluetooth_experimental: false
    bluetooth_kernel_experimental: false

  tasks:
    - name: Converge | Include bluetooth role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
