---
#
# RedHat Variables
#

__plymouth_packages:
  - 'plymouth'
  - 'plymouth-system-theme'

__plymouth_mkinitcpio_conf: ''
__plymouth_initramfs_command: 'dracut --regenerate-all --force'

__plymouth_grub_default_file: '/etc/default/grub'
__plymouth_grub_mkconfig_command: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
