---
#
# KeePassXC Secret Service Tasks
#

- name: Secret Service | Ensure global D-Bus services directory exists
  ansible.builtin.file:
    path: '/usr/local/share/dbus-1/services'
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: keepassxc_secret_service_global | bool

- name: Secret Service | Install globally
  ansible.builtin.copy:
    src: 'org.freedesktop.secrets.service'
    dest: '/usr/local/share/dbus-1/services/org.freedesktop.secrets.service'
    owner: root
    group: root
    mode: '0644'
  when: keepassxc_secret_service_global | bool

- name: Secret Service | Create user-specific D-Bus services directories
  ansible.builtin.file:
    path: '/home/{{ item.name }}/.local/share/dbus-1/services/'
    state: directory
    owner: '{{ item.name }}'
    group: '{{ item.group | default(item.name) }}'
    mode: '0755'
  when:
    - not keepassxc_secret_service_global | bool
    - item.secret_service | default(true)
  loop: '{{ keepassxc_users }}'
  loop_control:
    label: '{{ item.name }}'

- name: Secret Service | Install user-specific integration
  ansible.builtin.copy:
    src: 'org.freedesktop.secrets.service'
    dest: '/home/{{ item.name }}/.local/share/dbus-1/services/org.freedesktop.secrets.service'
    owner: '{{ item.name }}'
    group: '{{ item.group | default(item.name) }}'
    mode: '0644'
  when:
    - not keepassxc_secret_service_global | bool
    - item.secret_service | default(true)
  loop: '{{ keepassxc_users }}'
  loop_control:
    label: '{{ item.name }}'

- name: Secret Service | Remove user-specific integration
  ansible.builtin.file:
    path: '/home/{{ item.name }}/.local/share/dbus-1/services/org.freedesktop.secrets.service'
    state: absent
  when:
    - not keepassxc_secret_service_global | bool
    - not (item.secret_service | default(true))
  loop: '{{ keepassxc_users }}'
  loop_control:
    label: '{{ item.name }}'
