---
# Packages
__browser_firefox_package: 'firefox'
__browser_firefox_i18n_package: 'firefox-i18n-{{ browser_firefox_i18n }}'
__browser_chromium_package: 'chromium'

# AUR packages
__browser_aur_packages:
  librewolf: 'librewolf-bin'
  brave: 'brave-bin'
  tor: 'tor-browser'
  zen: 'zen-browser-bin'

# Policy paths
__browser_firefox_policies_path: '/usr/lib/firefox/distribution'
__browser_firefox_autoconfig_path: '/usr/lib/firefox/defaults/pref'
__browser_firefox_config_path: '/usr/lib/firefox'
__browser_librewolf_policies_path: '/usr/lib/librewolf/distribution'
__browser_chromium_policies_path: '/etc/chromium/policies'
__browser_brave_policies_path: '/etc/brave/policies'

# Firefox profile directory pattern (for find)
__browser_firefox_profile_pattern: '*.default-release'
__browser_librewolf_profile_pattern: '*.default-default'
