---
galaxy_info:
  author: Marc Straube
  description: Install imaging and scanning applications
  license: MIT

  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - imaging
    - scanning
    - sane
    - vuescan
    - desktop

dependencies: []
