---
galaxy_info:
  author: Marc Straube
  description: Install multimedia applications for audio and video
  license: MIT
  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - multimedia
    - video
    - audio
    - vlc
    - audacity
    - desktop

dependencies: []
