---
#
# Arch Linux Variables
#

__pipewire_packages:
  - pipewire

__pipewire_audio_packages:
  - pipewire-audio

__pipewire_session_managers:
  wireplumber: wireplumber
  pipewire-media-session: pipewire-media-session

__pipewire_pulse_package: pipewire-pulse
__pipewire_alsa_package: pipewire-alsa
__pipewire_jack_package: pipewire-jack
__pipewire_zeroconf_package: pipewire-zeroconf

__pipewire_bluetooth_packages:
  - pipewire-audio
  - libldac

__pipewire_32bit_packages:
  - lib32-pipewire
  - lib32-pipewire-jack

__pipewire_realtime_package: realtime-privileges
__pipewire_realtime_group: realtime

__pipewire_volume_control_packages:
  pavucontrol: pavucontrol
  none: ''

__pipewire_patchbay_packages:
  helvum: helvum
  qpwgraph: qpwgraph
  none: ''

__pipewire_pulseaudio_packages:
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth

__pipewire_config_dir: /etc/pipewire
__pipewire_user_config_dir: .config/pipewire

__pipewire_user_services:
  - pipewire.service
  - pipewire-pulse.service
  - wireplumber.service
