---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    display_manager_enabled: true
    display_manager_name: 'sddm'
    display_manager_service_enabled: false
    display_manager_autologin_enabled: false

  tasks:
    - name: Converge | Include display_manager role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
