---
#
# Debian Variables
#

# Shell packages
__shell_zsh_package: 'zsh'
__shell_fish_package: 'fish'
__shell_bash_completion_package: 'bash-completion'

# Zsh plugins
__shell_zsh_plugin_packages:
  completions: ''
  autosuggestions: 'zsh-autosuggestions'
  syntax-highlighting: 'zsh-syntax-highlighting'
  history-substring-search: ''

__shell_zsh_grml_package: ''

# Starship
__shell_starship_package: ''

# Additional tools
__shell_fzf_package: 'fzf'
__shell_zoxide_package: 'zoxide'
__shell_eza_package: ''
__shell_bat_package: 'bat'
__shell_fd_package: 'fd-find'
__shell_ripgrep_package: 'ripgrep'
__shell_tldr_package: 'tldr'

# Shell paths
__shell_paths:
  zsh: '/usr/bin/zsh'
  fish: '/usr/bin/fish'
  bash: '/bin/bash'
