---
#
# OS-independent Variables
#

# Shell packages
__shell_zsh_package: 'zsh'
__shell_fish_package: 'fish'
__shell_bash_completion_package: 'bash-completion'

# Shell paths
__shell_paths:
  zsh: '/usr/bin/zsh'
  fish: '/usr/bin/fish'
  bash: '/bin/bash'
