---
driver:
  name: podman
platforms:
  - name: multimedia-archlinux
    image: docker.io/marcstraube/archlinux-ansible:latest
    pre_build_image: true
    command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: rw,nosuid,nodev,size=65536k
      /tmp: rw,nosuid,nodev
  - name: multimedia-debian-trixie
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: rw,nosuid,nodev,size=65536k
      /tmp: rw,nosuid,nodev
  - name: multimedia-rocky-9
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: rw,nosuid,nodev,size=65536k
      /tmp: rw,nosuid,nodev
  - name: multimedia-rocky-10
    image: docker.io/geerlingguy/docker-rockylinux10-ansible:latest
    pre_build_image: true
    command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: rw,nosuid,nodev,size=65536k
      /tmp: rw,nosuid,nodev
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      multimedia-archlinux:
        ansible_python_interpreter: /usr/bin/python
      multimedia-debian-trixie:
        ansible_python_interpreter: /usr/bin/python3
      multimedia-rocky-9:
        ansible_python_interpreter: /usr/bin/python3
      multimedia-rocky-10:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      allow_broken_conditionals: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
