---
#
# Scanning Packages
#

__imaging_sane_package: sane-utils
__imaging_xsane_package: xsane
__imaging_simple_scan_package: simple-scan
__imaging_skanlite_package: skanlite

#
# Image Processing Packages
#

__imaging_imagemagick_package: imagemagick
__imaging_graphicsmagick_package: graphicsmagick
