---
- name: Firefox | Ensure Firefox policies directory exists
  ansible.builtin.file:
    path: '{{ __browser_firefox_policies_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Firefox | Deploy Firefox policies.json
  ansible.builtin.template:
    src: firefox-policies.json.j2
    dest: '{{ __browser_firefox_policies_path }}/policies.json'
    owner: root
    group: root
    mode: '0644'

- name: Firefox | Deploy Firefox autoconfig.js
  ansible.builtin.template:
    src: autoconfig.js.j2
    dest: '{{ __browser_firefox_autoconfig_path }}/autoconfig.js'
    owner: root
    group: root
    mode: '0644'
  when: browser_firefox_preferences | length > 0

- name: Firefox | Deploy Firefox firefox.cfg
  ansible.builtin.template:
    src: firefox.cfg.j2
    dest: '{{ __browser_firefox_config_path }}/firefox.cfg'
    owner: root
    group: root
    mode: '0644'
  when: browser_firefox_preferences | length > 0
