---
- name: Firefox | Ensure policies directory exists
  ansible.builtin.file:
    path: '{{ __browser_firefox_policies_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Firefox | Deploy policies.json
  ansible.builtin.template:
    src: firefox-policies.json.j2
    dest: '{{ __browser_firefox_policies_path }}/policies.json'
    owner: root
    group: root
    mode: '0644'
