---
galaxy_info:
  author: Marc Straube
  description: Install and configure shells (Zsh, Fish, Bash) and Starship prompt
  license: MIT
  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - shell
    - zsh
    - fish
    - starship
    - desktop

dependencies: []
