---
#
# RedHat Packages
#

__filemanagers_thunar_package: 'thunar'
__filemanagers_dolphin_package: 'dolphin'
__filemanagers_nautilus_package: 'nautilus'
__filemanagers_pcmanfm_package: 'pcmanfm'
__filemanagers_nemo_package: 'nemo'
__filemanagers_doublecmd_package: ''
