---
galaxy_info:
  author: Marc Straube
  description: Install terminal emulators (Ghostty, Alacritty, Kitty, Foot, Wezterm)
  license: MIT
  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - terminal
    - desktop
    - ghostty
    - alacritty
    - kitty

dependencies: []
