---
#
# Role Control
#

# Enable the filemanagers role
filemanagers_enabled: true

#
# GUI File Managers
#

# Enable Thunar (Xfce file manager)
filemanagers_thunar_enabled: false

# Enable Dolphin (KDE file manager)
filemanagers_dolphin_enabled: false

# Enable Nautilus (GNOME file manager)
filemanagers_nautilus_enabled: false

# Enable PCManFM (lightweight file manager)
filemanagers_pcmanfm_enabled: false

# Enable Nemo (Cinnamon file manager, fork of Nautilus)
filemanagers_nemo_enabled: false

# Enable Double Commander (two-panel file manager)
filemanagers_doublecmd_enabled: false
