---
galaxy_info:
  author: Marc Straube
  description: Install gaming platforms and emulators
  license: MIT
  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - gaming
    - lutris
    - retroarch
    - emulation
    - desktop

dependencies: []
