---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    # Plymouth requires mkinitcpio/dracut + GRUB — impossible in Docker.
    # Disable role entirely for molecule tests.
    plymouth_enabled: false

  tasks:
    - name: Converge | Include plymouth role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
