---
#
# PipeWire Main Tasks
#

- name: Main | Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'
  tags:
    - pipewire

- name: Main | Import cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  when:
    - pipewire_enabled | bool
    - pipewire_remove_pulseaudio_enabled | bool
  tags:
    - pipewire
    - pipewire:cleanup

- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  when: pipewire_enabled | bool
  tags:
    - pipewire
    - pipewire:install

- name: Main | Import configure tasks
  ansible.builtin.import_tasks: configure.yml
  when:
    - pipewire_enabled | bool
    - pipewire_custom_config_enabled | bool
  tags:
    - pipewire
    - pipewire:configure

- name: Main | Import realtime tasks
  ansible.builtin.import_tasks: realtime.yml
  when:
    - pipewire_enabled | bool
    - pipewire_realtime_enabled | bool
  tags:
    - pipewire
    - pipewire:realtime

- name: Main | Import service tasks
  ansible.builtin.import_tasks: service.yml
  when: pipewire_enabled | bool
  tags:
    - pipewire
    - pipewire:service
