---
- name: Install | GIMP
  ansible.builtin.package:
    name: '{{ __graphics_apps_gimp_package }}'
    state: present
  when:
    - graphics_apps_gimp_enabled | bool
  retries: 3
  delay: 5

- name: Install | GIMP plugins
  ansible.builtin.package:
    name: '{{ graphics_apps_gimp_plugins }}'
    state: present
  when:
    - graphics_apps_gimp_enabled | bool
    - graphics_apps_gimp_plugins | length > 0
  retries: 3
  delay: 5

- name: Install | Krita
  ansible.builtin.package:
    name: '{{ __graphics_apps_krita_package }}'
    state: present
  when:
    - graphics_apps_krita_enabled | bool
    - __graphics_apps_krita_package | default('') | length > 0
  retries: 3
  delay: 5

- name: Install | Inkscape
  ansible.builtin.package:
    name: '{{ __graphics_apps_inkscape_package }}'
    state: present
  when:
    - graphics_apps_inkscape_enabled | bool
  retries: 3
  delay: 5

- name: Install | XnConvert from AUR (Arch)
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: '{{ __graphics_apps_aur_packages.xnconvert }}'
    state: present
  when:
    - ansible_facts['os_family'] == 'Archlinux'
    - graphics_apps_xnconvert_enabled | bool
  retries: 3
  delay: 5

- name: Install | XnView from AUR (Arch)
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: '{{ __graphics_apps_aur_packages.xnview }}'
    state: present
  when:
    - ansible_facts['os_family'] == 'Archlinux'
    - graphics_apps_xnview_enabled | bool
  retries: 3
  delay: 5
