---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    terminal_enabled: true
    terminal_emulators:
      - 'kitty'
    terminal_default: 'kitty'

  tasks:
    - name: Converge | Include terminal role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
