---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Prepare | Update package cache (Arch)
      community.general.pacman:
        update_cache: true
      changed_when: false
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Prepare | Update package cache (Debian)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'

    - name: Prepare | Update package cache (RedHat)
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Prepare | Create aur_builder user (Arch)
      ansible.builtin.user:
        name: aur_builder
        group: wheel
        create_home: true
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Prepare | Configure sudoers for aur_builder (Arch)
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: ALL'
        create: true
        mode: '0440'
        validate: 'visudo -cf %s'
      when: ansible_facts['os_family'] == 'Archlinux'
