---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify | Confirm role completed successfully
      ansible.builtin.assert:
        that: true
        fail_msg: 'AI role did not complete'
