---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    #
    # Repository Setup
    #

    - name: Prepare | Install EPEL repository (RedHat)
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Prepare | Enable CRB repository (RedHat)
      ansible.builtin.command:
        cmd: dnf config-manager --set-enabled crb
      changed_when: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Prepare | Enable contrib component (Debian)
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/debian.sources
        regexp: '^(Components: main)$'
        replace: '\1 contrib'
      when: ansible_facts['os_family'] == 'Debian'

    #
    # Package Cache Updates
    #

    - name: Prepare | Update package cache (Arch)
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Prepare | Update package cache (Debian)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Prepare | Update package cache (RedHat)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'
