---
- name: Install | OpenSCAD
  ansible.builtin.package:
    name: '{{ __cad_openscad_package }}'
    state: present
  when:
    - cad_openscad_enabled | bool
    - __cad_openscad_package | default('') | length > 0

- name: Install | FreeCAD
  ansible.builtin.package:
    name: '{{ __cad_freecad_package }}'
    state: present
  when:
    - cad_freecad_enabled | bool
    - __cad_freecad_package | default('') | length > 0

- name: Install | LibreCAD
  ansible.builtin.package:
    name: '{{ __cad_librecad_package }}'
    state: present
  when:
    - cad_librecad_enabled | bool
    - __cad_librecad_package | default('') | length > 0

- name: Install | QCAD
  ansible.builtin.package:
    name: '{{ __cad_qcad_package }}'
    state: present
  when:
    - cad_qcad_enabled | bool
    - __cad_qcad_package | default('') | length > 0

- name: Install | Blender
  ansible.builtin.package:
    name: '{{ __cad_blender_package }}'
    state: present
  when:
    - cad_blender_enabled | bool
    - __cad_blender_package | default('') | length > 0

- name: Install | KiCad
  ansible.builtin.package:
    name: '{{ __cad_kicad_package }}'
    state: present
  when:
    - cad_kicad_enabled | bool
    - __cad_kicad_package | default('') | length > 0
